config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'

  resources :users, only: [:new, :create, :edit, :update] do
    resources :expenses, only: [:create]
  end

  delete '/expenses/:id' => 'expenses#destroy', as: 'remove'
  
  get '/dashboard' => 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user

  validates :cost, :due_date, :details, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :name, :email, :budget, presence: true
  validates :password, presence: true, :on => :create
  validates :password, confirmation: true
  validates :password_confirmation, presence: true, :on => :create
  validates :email, uniqueness: true

  has_many :expenses

  def total_expense_cost
    expenses.pluck(:cost).inject(:+)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def create
    @user    = User.find(params[:user_id])
    @expense = @user.expenses.new(expense_params)
    if @expense.save
      flash[:info]  = "Successfully created an expense."
      redirect_to dashboard_path
    else
      flash[:danger] = "Make sure all required fields are filled in."
      redirect_to dashboard_path
    end
  end

  def destroy
    expense = Expense.find(params[:id])
    expense.destroy

    flash[:info] = "Removed expense."
    redirect_to dashboard_path
  end

  private

  def expense_params
    params.require(:expense).permit(:cost, :due_date, :details, :user_id)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Logged in as #{@user.name}."
      redirect_to dashboard_path
    else
      flash[:danger] = "Login Failed."
      redirect_to login_path
    end
  end

  def destroy
    reset_session
    flash[:success] = "Successfully Logged Out."
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update]

  def show
    if session[:user_id].nil?
      render file: "/public/404"
    else
      @user = User.find(session[:user_id])
      @expense = Expense.new
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Successfully Registered #{@user.name}! This is your budget page."
      redirect_to dashboard_path
    else
      flash[:danger] = "Please make sure all fields are correctly filled out."
      render :new
    end
  end

  def edit
    render file: "/public/404" if session[:user_id] != params[:id].to_i      
  end

  def update
    @user.update(user_params)
    if @user.save
      flash[:success] = "Successfuly changed budget to $#{@user.budget}."
      redirect_to dashboard_path
    else
      flash[:danger] = 'Must submit a new budget.'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :budget, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
    <%= content_tag :div, sanitize(msg), class: "alert alert-#{name}" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse bg-inverse">
  <img class="financial-planner-pic" src="http://www.freeiconspng.com/uploads/money-icon-29.png" />
  <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Home', root_path, class: "btn btn-default" %></li>
    <% if !current_user %>
      <li><%= link_to 'Register', new_user_path, class: "btn btn-default"%></li>
      <li class="welcome-btn"><%= link_to 'Login', login_path, class: "btn btn-default" %></li>
    <% else %>
      <li>
        <%= link_to "Dashboard", dashboard_path, class:'btn btn-default' %>
      </li>
      <li class="welcome-btn"><%= link_to "Logout", logout_path, method: :DELETE, class: "btn btn-default" %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Financial Planner</title>
    <%= favicon_link_tag 'money-icon-29.png' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= render partial: "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class='container'>
  <div class = "col-md-offset-4 col-md-4">
  <h1 style="text-align: center"> Edit Budget </h1>
    <%= bootstrap_form_for @user do |f| %>
      <%= f.number_field :budget, placeholder: 'Your New Budget', skip_label: true %>
      <%= f.submit 'Submit', {class: "btn btn-info btn-block"}%>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class = "col-md-offset-3 col-md-6 text-center">
  <h1>Register New Account</h1>
</div>
<div class = "col-md-offset-4 col-md-4">
  <%= bootstrap_form_for @user do |f| %>
    <%= f.text_field :name, placeholder: 'Your Name', skip_label: true %>
    <%= f.email_field :email, placeholder: 'Your email: name@example.com', skip_label: true %>
    <%= f.number_field :budget, placeholder: 'Your Budget', skip_label: true %>
    <%= f.password_field :password, placeholder: 'Your new password', skip_label: true %>
    <%= f.password_field :password_confirmation, placeholder: 'Confirm Password.', skip_label: true %>
    <%= f.submit 'Register', {class: "btn btn-success btn-block"}%>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='container'>
  <h1><%= @user.name %>'s Financial Planner</h1>
  <div class='budget-widget col-md-6'>
    <h2 id='budget'>Monthly Budget: <strong>$<%= @user.budget %></strong></h2>
    <% if @user.expenses.empty? %>
      <h2 id='expenses'>Total Expenses: $0.00</h2>
    <% else %>
      <h2 id='expenses'>Total Expenses: $<%= @user.total_expense_cost %></h2>
    <% end %>
    <h2 class='budget-expense-diff'>Budget remaining: </h2>
  </div>
  <div class = "col-md-6">
    <h3>Add an expense to your financial planner:</h3>
    <%= bootstrap_form_for [@user, @expense] do |f| %>
      <%= f.number_field :cost, placeholder: 'Expense Cost', skip_label: true %>
      <%= f.date_field :due_date, placeholder: 'Expense Cost', skip_label: true %> 
      <%= f.text_field :details, placeholder: 'Expense description', skip_label: true, size: '30x15' %>
      <%= f.submit 'Add Expense', {class: "btn btn-success btn-block"} %>
    <% end %>
    <p class = "login-or-separator text-center"><strong>OR need to change your budget?</strong></p>
    <%= link_to 'Update Budget', edit_user_path(@user), class:"btn btn-warning btn-block"%>
</div>

  </div>
</div>

<div class='container'>
  <table class="table table-hover expenses-table">
    <tr>
      <th> Cost </th>
      <th> Due Date </th>
      <th> Details </th>
    </tr>
    <% @user.expenses.each do |expense| %>
    <tr>
      <td> $<%= expense.cost %> </td>
      <td> <%= expense.due_date %> </td>
      <td> <%= expense.details %> </td>
      <td> <%= link_to "Remove", "/expenses/#{expense.id}", method: :delete, class:'btn btn-warning btn-xs' %> </td>
    <% end %>
    </tr>
  </table>
</div>

app/views/welcome/index.html.erb
<div class='container'>
  <div class='col-md-6'>
    <img class='img-responsive welcome-img' src='https://timedotcom.files.wordpress.com/2015/10/151028_adv_howfinancialplanner.jpg?quality=85' />
  </div>
  <div class='col-md-6'>
    <h1>Faq</h1>
    <p>
      Welcome to <a target='_blank' href='https://www.github.com/Dpalazzari'>my</a> financial planning app. Feel free to register and start to track your budget!
      Your information is safe and secure, and so long as you do not share your password, no one else will know your financial details. Enjoy!
    </p>
    <p>
      If you have any add-ons, bugs to report, or feel that a certain feature is missing, I invite you reach out to me and share your thoughts. Incidentally, 
      if you have coding talent, add the change, fix the bug, and create a pull request! Cheers.
    </p>
    <br>
    <br>
    <div>
      <h3 class='add-resources'>Additional resources of the Creator:</h3>
      <a href="https://github.com/Dpalazzari" target="_blank"><img class='img-circle resources' src="https://image.flaticon.com/icons/svg/25/25231.svg" /></a>
      <a href="https://www.linkedin.com/in/drewpalazzari/" target="_blank"><img class='img-circle resources' src="https://image.flaticon.com/icons/svg/34/34405.svg" /></a>
      <a href="https://www.turing.io/alumni/drew-palazzari" target="_blank"><img class='img-circle resources' src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-340/turing.png" /></a>
    </div>
  </div>
</div>